AWSTemplateFormatVersion: "2010-09-09"
Description: Create a private S3 bucket.

Parameters:
  BucketName:
    Description: Name of the bucket
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

Outputs:
  BucketArn:
    Description: The new bucket ARN
    Value: !GetAtt Bucket.Arn
  WebsiteUrl:
    Description: The URL of the website
    Value: !GetAtt Bucket.WebsiteURL
